#!/usr/bin/env python3
"""Paired ReSplat A/B diagnostic: local-identity vs pose-conditioned inference.

This script intentionally leaves the established execution baseline untouched.
It reuses the same build_system(), MAC-VO sequence/frontend, and persistent
ResplatPacketGenerator as run_pipeline_execution_benchmark.py, but does not run
the GraphDECO backend.

For every frame whose MAC-VO pose becomes committed, the exact same StereoFrameInput
is evaluated twice with paired RNG state:

  A) output_frame="left_camera_local"
     -> ReSplat sees left pose = identity.

  B) output_frame="world", T_world_from_left=<MAC-VO committed pose>
     -> ReSplat sees the committed camera pose before encoding.

Each arm is rendered with ReSplat's own decoder at the target view generated by
that arm, then scored against the identical post-shim left target image.

The paired RNG snapshot/restore makes A and B consume the same random state while
leaving the global RNG progression equivalent to one A inference per evaluated
frame. This isolates the effect of supplying the pose to ReSplat as closely as
possible without changing the baseline implementation.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
import time
from dataclasses import replace
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image

import run_async_pipeline as base
from async_pipeline.contracts import PoseEstimate, StereoFrameInput


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default="Config/Pipeline/MACVO_ReSplat_Serial_Report_P000_0_50.yaml",
        help="Same pipeline YAML used by run_pipeline_execution_benchmark_repro.py.",
    )
    parser.add_argument(
        "--set",
        dest="overrides",
        action="append",
        default=[],
        metavar="SECTION.KEY=VALUE",
        help="Override an existing pipeline key using the standard runner syntax.",
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=None,
        help="Output directory. Defaults to <work_dir>/resplat_local_vs_pose_ab.",
    )
    parser.add_argument(
        "--include_test_frames",
        action="store_true",
        help="Also evaluate frames marked test by the baseline split.",
    )
    parser.add_argument(
        "--max_pairs",
        type=int,
        default=0,
        help="Stop after this many evaluated A/B pairs; 0 means no limit.",
    )
    parser.add_argument(
        "--save_gt",
        action="store_true",
        help="Save the exact post-shim left target image used for scoring.",
    )
    return parser.parse_args()


def seed_all() -> int:
    seed = int(os.environ.get("PIPELINE_BENCHMARK_SEED", "0"))
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    os.environ.setdefault("PYTHONHASHSEED", str(seed))
    return seed


def snapshot_rng() -> dict[str, Any]:
    state: dict[str, Any] = {
        "python": random.getstate(),
        "numpy": np.random.get_state(),
        "torch_cpu": torch.get_rng_state(),
    }
    if torch.cuda.is_available():
        state["torch_cuda"] = torch.cuda.get_rng_state_all()
    return state


def restore_rng(state: dict[str, Any]) -> None:
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.set_rng_state(state["torch_cpu"])
    if torch.cuda.is_available() and "torch_cuda" in state:
        torch.cuda.set_rng_state_all(state["torch_cuda"])


def save_rgb(tensor: torch.Tensor, path: Path) -> None:
    image = (
        tensor.detach()
        .float()
        .clamp(0.0, 1.0)
        .mul(255.0)
        .round()
        .to(torch.uint8)
        .permute(1, 2, 0)
        .cpu()
        .numpy()
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(image).save(path)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    keys: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                keys.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def rotation_angle_deg(T: torch.Tensor) -> float:
    R = T[:3, :3].detach().float().cpu()
    trace = float(torch.trace(R))
    cos_theta = max(-1.0, min(1.0, (trace - 1.0) * 0.5))
    return math.degrees(math.acos(cos_theta))


def render_and_score(packet_generator, result, compute_psnr, compute_ssim):
    batch = result.batch
    target = batch["target"]
    h = int(target["image"].shape[-2])
    w = int(target["image"].shape[-1])

    start = time.perf_counter()
    with torch.inference_mode():
        render_out = packet_generator.model.decoder.forward(
            result.gaussians,
            target["extrinsics"],
            target["intrinsics"],
            target["near"],
            target["far"],
            (h, w),
            depth_mode=None,
        )
    if torch.cuda.is_available():
        torch.cuda.synchronize(packet_generator.device)
    render_sec = time.perf_counter() - start

    pred_all = render_out.color.float().clamp(0.0, 1.0)
    gt_all = target["image"].float().clamp(0.0, 1.0)
    pred_flat = pred_all.reshape(-1, *pred_all.shape[-3:])
    gt_flat = gt_all.reshape(-1, *gt_all.shape[-3:])
    psnr = float(compute_psnr(gt_flat, pred_flat).mean().item())
    ssim = float(compute_ssim(gt_flat, pred_flat).mean().item())

    return {
        "psnr": psnr,
        "ssim": ssim,
        "render_sec": render_sec,
        "pred": pred_all[0, 0].detach(),
        "gt": gt_all[0, 0].detach(),
        "target_intrinsics": target["intrinsics"].detach(),
        "target_extrinsics": target["extrinsics"].detach(),
        "context_intrinsics": batch["context"]["intrinsics"].detach(),
        "context_extrinsics": batch["context"]["extrinsics"].detach(),
        "target_image": target["image"].detach(),
    }


def main() -> None:
    args = parse_args()
    seed = seed_all()

    root = Path(__file__).resolve().parent
    config_path = base.absolute(args.config, root)
    config = base.load_yaml(config_path)
    for item in args.overrides:
        if "=" not in item:
            raise ValueError(f"invalid override {item!r}")
        key, raw = item.split("=", 1)
        base.nested_set(config, key, base.normalize_override_value(key, raw))

    resolved = base.resolve(config, root)
    base.validate_paths(resolved)

    work_dir = Path(resolved["paths"]["work_dir"]).expanduser().resolve()
    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else work_dir / "resplat_local_vs_pose_ab"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "resolved_config.json").write_text(
        json.dumps(resolved, indent=2), encoding="utf-8"
    )

    # Same component construction as the established execution baseline.
    template = base.build_system(resolved)
    pose_frontend = template.pose_frontend
    packet_generator = template.packet_generator

    init_start = time.perf_counter()
    pose_frontend.initialize()
    packet_generator.initialize()
    initialization_sec = time.perf_counter() - init_start

    resplat_repo = Path(resolved["paths"]["resplat_repo"])
    if str(resplat_repo) not in sys.path:
        sys.path.insert(0, str(resplat_repo))
    from src.evaluation.metrics import compute_psnr, compute_ssim

    pending_inputs: dict[int, StereoFrameInput] = {}
    rows: list[dict[str, Any]] = []
    skipped_test = 0
    skipped_invalid_pose = 0
    first_debug: dict[str, Any] | None = None
    stop_requested = False

    def evaluate_estimate(estimate: PoseEstimate) -> None:
        nonlocal skipped_test, skipped_invalid_pose, first_debug, stop_requested

        seq_idx = int(estimate.descriptor.sequence_index)
        stereo_input = pending_inputs.pop(seq_idx, None)
        if stereo_input is None:
            raise RuntimeError(
                f"Missing StereoFrameInput for committed pose sequence_index={seq_idx}"
            )

        descriptor = stereo_input.descriptor
        if descriptor.is_test and not args.include_test_frames:
            skipped_test += 1
            return
        if not estimate.valid:
            skipped_invalid_pose += 1
            return

        estimate.validate()
        T_world_from_left = estimate.T_world_from_left.detach().cpu().float()

        # Pair the random states. After B, restore the post-A state so the global
        # RNG progression is equivalent to one local inference per evaluated frame.
        rng_before = snapshot_rng()
        local_result = packet_generator.infer(
            stereo_input,
            output_frame="left_camera_local",
        )
        rng_after_local = snapshot_rng()

        restore_rng(rng_before)
        world_result = packet_generator.infer(
            stereo_input,
            output_frame="world",
            T_world_from_left=T_world_from_left,
        )
        restore_rng(rng_after_local)

        local_metrics = render_and_score(
            packet_generator, local_result, compute_psnr, compute_ssim
        )
        world_metrics = render_and_score(
            packet_generator, world_result, compute_psnr, compute_ssim
        )

        target_image_max_abs_diff = float(
            (local_metrics["target_image"] - world_metrics["target_image"])
            .abs()
            .max()
            .item()
        )
        target_K_max_abs_diff = float(
            (local_metrics["target_intrinsics"] - world_metrics["target_intrinsics"])
            .abs()
            .max()
            .item()
        )

        frame_index = int(descriptor.frame_index)
        save_rgb(local_metrics["pred"], output_dir / "renders_local" / f"{frame_index:06d}.png")
        save_rgb(world_metrics["pred"], output_dir / "renders_pose_conditioned" / f"{frame_index:06d}.png")
        if args.save_gt:
            save_rgb(local_metrics["gt"], output_dir / "gt" / f"{frame_index:06d}.png")

        t_norm = float(torch.linalg.vector_norm(T_world_from_left[:3, 3]).item())
        r_deg = rotation_angle_deg(T_world_from_left)
        row = {
            "sequence_index": seq_idx,
            "frame_index": frame_index,
            "is_test": bool(descriptor.is_test),
            "pose_valid": bool(estimate.valid),
            "pose_translation_norm_m": t_norm,
            "pose_rotation_angle_deg_from_identity": r_deg,
            "num_gaussians_local": int(local_result.packet.num_gaussians),
            "num_gaussians_world": int(world_result.packet.num_gaussians),
            "local_psnr": float(local_metrics["psnr"]),
            "world_psnr": float(world_metrics["psnr"]),
            "delta_psnr_world_minus_local": float(world_metrics["psnr"] - local_metrics["psnr"]),
            "local_ssim": float(local_metrics["ssim"]),
            "world_ssim": float(world_metrics["ssim"]),
            "delta_ssim_world_minus_local": float(world_metrics["ssim"] - local_metrics["ssim"]),
            "local_inference_sec": float(local_result.inference_sec),
            "world_inference_sec": float(world_result.inference_sec),
            "local_render_sec": float(local_metrics["render_sec"]),
            "world_render_sec": float(world_metrics["render_sec"]),
            "target_image_max_abs_diff": target_image_max_abs_diff,
            "target_intrinsic_max_abs_diff": target_K_max_abs_diff,
        }
        rows.append(row)

        if first_debug is None:
            first_debug = {
                "frame_index": frame_index,
                "baseline_input_shape": list(stereo_input.left_image.shape),
                "baseline_intrinsic_pixel": stereo_input.intrinsic_pixel.detach().cpu().tolist(),
                "baseline_m": float(stereo_input.baseline_m),
                "T_world_from_left": T_world_from_left.tolist(),
                "local_context_extrinsics": local_metrics["context_extrinsics"].cpu().tolist(),
                "world_context_extrinsics": world_metrics["context_extrinsics"].cpu().tolist(),
                "local_target_extrinsics": local_metrics["target_extrinsics"].cpu().tolist(),
                "world_target_extrinsics": world_metrics["target_extrinsics"].cpu().tolist(),
                "local_target_intrinsics": local_metrics["target_intrinsics"].cpu().tolist(),
                "world_target_intrinsics": world_metrics["target_intrinsics"].cpu().tolist(),
                "target_image_max_abs_diff": target_image_max_abs_diff,
                "target_intrinsic_max_abs_diff": target_K_max_abs_diff,
                "resplat_image_shape": list(packet_generator.image_shape),
                "resplat_near": float(packet_generator.near),
                "resplat_far": float(packet_generator.far),
                "resplat_refine_steps": int(packet_generator.config.refine_steps),
                "resplat_input_mode": str(packet_generator.config.input_mode),
            }
            (output_dir / "first_pair_debug.json").write_text(
                json.dumps(first_debug, indent=2), encoding="utf-8"
            )

        print(
            f"[A/B {len(rows):03d}] frame={frame_index:04d} test={descriptor.is_test} "
            f"local={local_metrics['psnr']:.2f}dB world={world_metrics['psnr']:.2f}dB "
            f"delta={world_metrics['psnr'] - local_metrics['psnr']:+.2f}dB "
            f"|t|={t_norm:.3f}m R={r_deg:.1f}deg",
            flush=True,
        )

        del local_result, world_result, local_metrics, world_metrics

        if args.max_pairs > 0 and len(rows) >= args.max_pairs:
            stop_requested = True

    total_start = time.perf_counter()
    for descriptor, frame, stereo_input, _observation in pose_frontend.iter_frames():
        descriptor = replace(descriptor, is_test=template.config.is_test(descriptor))
        stereo_input.descriptor = descriptor
        pending_inputs[int(descriptor.sequence_index)] = stereo_input

        for estimate in pose_frontend.process(descriptor, frame):
            evaluate_estimate(estimate)
            if stop_requested:
                break
        if stop_requested:
            break

    # Only flush the delayed final pose when the normal sequence loop completed.
    if not stop_requested:
        for estimate in pose_frontend.terminate():
            evaluate_estimate(estimate)
            if stop_requested:
                break

    total_sec = time.perf_counter() - total_start
    packet_generator.close()

    if not rows:
        raise RuntimeError("No valid A/B pairs were evaluated")

    local_psnr = np.asarray([r["local_psnr"] for r in rows], dtype=np.float64)
    world_psnr = np.asarray([r["world_psnr"] for r in rows], dtype=np.float64)
    local_ssim = np.asarray([r["local_ssim"] for r in rows], dtype=np.float64)
    world_ssim = np.asarray([r["world_ssim"] for r in rows], dtype=np.float64)

    summary = {
        "protocol": (
            "Same MAC-VO sequence/frontend + same persistent ReSplat generator. "
            "Paired RNG A: left_camera_local(identity pose before encoder); "
            "B: world(MAC-VO T_world_from_left before encoder). No GraphDECO backend."
        ),
        "seed": seed,
        "config": str(config_path),
        "include_test_frames": bool(args.include_test_frames),
        "num_pairs": len(rows),
        "num_skipped_test_frames": skipped_test,
        "num_skipped_invalid_pose": skipped_invalid_pose,
        "average_local_psnr": float(local_psnr.mean()),
        "average_world_psnr": float(world_psnr.mean()),
        "average_delta_psnr_world_minus_local": float((world_psnr - local_psnr).mean()),
        "median_delta_psnr_world_minus_local": float(np.median(world_psnr - local_psnr)),
        "average_local_ssim": float(local_ssim.mean()),
        "average_world_ssim": float(world_ssim.mean()),
        "average_delta_ssim_world_minus_local": float((world_ssim - local_ssim).mean()),
        "world_better_psnr_fraction": float(np.mean(world_psnr > local_psnr)),
        "max_target_image_abs_diff": float(max(r["target_image_max_abs_diff"] for r in rows)),
        "max_target_intrinsic_abs_diff": float(max(r["target_intrinsic_max_abs_diff"] for r in rows)),
        "average_local_inference_sec": float(np.mean([r["local_inference_sec"] for r in rows])),
        "average_world_inference_sec": float(np.mean([r["world_inference_sec"] for r in rows])),
        "initialization_sec": initialization_sec,
        "total_ab_sec": total_sec,
        "first_pair_debug": first_debug,
    }
    write_csv(output_dir / "per_frame_ab_metrics.csv", rows)
    (output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    print("\n===== ReSplat local-vs-pose-conditioned A/B summary =====", flush=True)
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
