type: TartanAir_NoIMU
name: TartanAirV1_Challenge_SH002

args:
  root: /home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo/SH002
  compressed: true
  gtDepth: false
  gtPose: false
  gtFlow: false
