type: TartanAir_NoIMU
name: TartanAirV1_Challenge_SH004

args:
  root: /home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo/SH004
  compressed: true
  gtDepth: false
  gtPose: false
  gtFlow: false
