type: TartanAir_NoIMU
name: TartanAirV1_Challenge_SE000

args:
  root: /home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo/SE000
  compressed: true
  gtDepth: false
  gtPose: false
  gtFlow: false
