type: TartanAir_NoIMU
name: TartanAirV1_Challenge_SE001

args:
  root: /home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo/SE001
  compressed: true
  gtDepth: false
  gtPose: false
  gtFlow: false
